version: '3.3'

services:
  client:
    container_name: client
    image: client
    volumes:
      - ./frontend
    ports:
      - "3000:3000"
  server:
    container_name: server
    image: server:latest
    volumes:
      - ./backend
      - ./backend/test.db
    ports:
    - "5000:5000"