name: Compose workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client
        run: docker build -f ./frontend/Dockerfile -t client .
      - name: Build server 
        run: docker build -f ./backend/Dockerfile -t server . 
      - name: Build stack
        run: docker-compose up -d
      - name: Test
        run: docker run --network client appropriate/curl -s --retry 10 --retry-conrefused https://localhost:3000
        # run: docker run --network container:server appropriate/curl -s --retry 10 --retry-conrefused https://localhost:5000
