name: Compose workflow

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build client
        run: docker build -f ./frontend/Dockerfile -t client .
      - name: Build server 
        run: docker build -f ./backend/Dockerfile -t server . 
      - name: Build stack
        run: docker-compose up -d
        
      # - name: Connect to Heroku
      #   with: 
      #     heroku_email: "fslkmemoe@protonmail.com"
      #     heroku_api_key: d2f50875-2aaf-41a7-a671-19c8c6cdd479
      #     heroku_app_name: cs484-final
      #   run: 
      #     - heroku: git::remote -- app $heroku_app_name
      # - name: push to heroku
      #   run: git push heroku master 
        